version: 2.1

defaults: &defaults
  working_directory: ~/postcss-themed
  docker:
    - image: node:20
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'

aliases:
  # Circle related commands
  - &restore-cache
    keys:
      - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  - &save-cache
    key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
    paths:
      - .pnpm-store
  - &setup
    name: Install pnpm package manager
    command: |
      npm install --global corepack@latest
      corepack enable
      corepack prepare pnpm@latest-10 --activate
      pnpm config set store-dir .pnpm-store
  - &pnpm
    name: Install Dependencies
    command: pnpm install
  - &lint
    name: Lint
    command: pnpm lint
  - &test
    name: Test
    command: pnpm test
  - &build
    name: Build
    command: pnpm build

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *setup
      - run: *pnpm
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-themed
      - run: *setup
      - run: *build
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-themed
      - run: *setup
      - run: *lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-themed
      - run: *setup
      - run: *test
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-themed
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: *setup
      - run:
          name: Release
          command: pnpm run release

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - build:
          requires:
            - install

      - lint:
          requires:
            - build

      - test:
          requires:
            - build

      - release:
          requires:
            - test
            - lint
